### ISSUE TITLE
Issue on authentication

### ISSUE THREAD

**Issue by vohoangnam997** [Octoberfest7/TeamsPhisher#12] opened 2023-07-07 03:03 UTC
I got this error below:                                                                             
Reading target email list..................................................[+] SUCCESS!                                                                   
Fetching Bearer token for Teams............................................[-] AADSTS50034: The user account {EmailHidden} does not exist in the 667d9ece-a83f-49d2-9b96-722ed643c25f directory. To sign into this application, the account must be added to the directory.                                         
Trace ID: 05cb4c6d-1567-46da-b272-a069972a4c00                               
Correlation ID: f0566341-6b34-46d9-a8da-7f83e7817bac                         
Timestamp: 2023-07-07 02:51:50Z 
How can I be successful on authenticating my login account?

**Comment by Octoberfest7** [comment] 2023-07-07 03:54
Hard to say what the issue is. As a shot in the dark, maybe the account you are using is a guest in the tenant? Or some new strangeness with a custom domain not resolving properly.

**Closed** 2023-07-09 03:36 UTC
